version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app123456
  web:
    build:
      comend: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code/
      ports:
        -"8000:8000"
      depends_on:
        -db