# Generated by Django 4.0.2 on 2022-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='app_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
